### ISSUE TITLE
Create generalized data update interface with differencing

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#129]
The differencing of the data in the database with the data obtained from the data source should be generalized and encapsulated by the interface. An implementer of the interface (a college) would then only need to provide information on the current state, and the interface would handle updating the database accordingly.

**Comment by JGrippo** [comment]
Updated AC:

New catalog adapter solution should consist of:

- An interface (abstract class)
- A client
Diffing and updating the database should be generalized and moved to a new catalog client so that this behavior does not have to be re-implemented for different sources. The implementation of the catalog interface is then only responsible for providing the current state of the catalog (to the client).

The implementation(s) of the interface should not be a part of this repository, but should exist as gems created by the maintainer of the relevant YACS distribution, similar to how OAuth providers are distributed

**Comment by copperwater** [comment]
@Bad-Science I know some work has been done on this, can you provide an update?
