### ISSUE TITLE
Input comma separated list of CRNs to quickly load a previously designed schedule

### ISSUE THREAD

**Issue by PatrickLove** [YACS-RCOS/yacs#174]

**Comment by copperwater** [comment]
This behavior should be covered by schedule links, which can load a set of schedules and can be bookmarked easily. This feature is mostly complete. See pull request #149.

I want to discuss this with the team before closing this as a duplicate, but I don't think we have a specific need for generating a schedule from CRNs if schedule links are implemented.

**Comment by copperwater** [comment]
This should be all taken care of with schedule links. It uses section IDs rather than CRNs, but I don't think that's particularly important? The links let you copy and bookmark schedules, and revisit ones by revisiting that URL. 

Closing this, since I think the links fulfill what was being requested.
