### ISSUE TITLE
Move Frontend to its own Repo

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs#217]
The front end no longer has any dependencies on Rails or Sprockets and can be easily moved over to a modern javascript toolchain. Therefore it is now possible to move the frontend to its own repo. This isn't terribly urgent, but it should be on our roadmap.

The only small challenge will be getting the end to end (cucumber) tests to work, but this should actually be pretty easy because the webdriver can be instructed to visit any arbitrary address. This may call for environment specific docker-compose overrides, but that is something we should really have anyway.

Food for thought: Should the end-to-end tests live in their own repository / environment?

**Comment by copperwater** [comment]
I'm somewhat hesitant to agree with this because splitting into a separate repository brings some administrative issues: we have 1 team, not 2; the frontend issues would have to stay on this repository; efforts to implement big new features like conflicts would need to be coordinated between the two repositories. 

On the other hand, I can see several benefits: the front end could be deployed independently; running Travis or whatever CI tools would be substantially faster; we would be able to use whatever toolchain we want.

We would want to implement this probably as a git subtree, and it'd entail installing a new toolchain that would run in its own docker container on the backend. It should be done AFTER the Schedule library is made separate from YACS and given its own repo, because it would be silly to have schedule.js stored under YACS and not the actual YACS frontend.

**Comment by Bad-Science** [comment]
All fair points. We can sit on it but ultimately I think it best fits with the deployment strategy and architecture we are going for. 

And it actually wouldn't be contingent on moving Schedule.js to its own repo. schedule.js and all of the vendor'd js files would move with the frontend to the new repo. If anything it might be easiest to move schedule.js to its own repo at the same time (but it would not be strictly necessary).

**Comment by Bad-Science** [comment]
This is now in progress on the https://github.com/YACS-RCOS/yacs-web repo. We will use Angular 4 with Typescript.

**Comment by Bad-Science** [comment]
Spring cleaning! This can definitely be closed. The angular frontend has been in active development for a while now, and the old frontend is definitely a no-fix.
