### ISSUE TITLE
Searching by professor name does not work with hyphens

### ISSUE THREAD

**Issue by milo-trujillo** [YACS-RCOS/yacs#265]
Yacs displays one professor as "costelloe-kuehn", but searching for "costelloe-kuehn" returns no results. Searching for "costelloe" finds all his classes. My guess is search does not work correctly when the name contains a hyphen.

**Comment by Bad-Science** [comment]
Hey @milo-trujillo ! Thanks for pointing this out! This is a bit of an oversight on my part - the SQL injection filtering is a little overzealous. We'll have it fixed soon.

**Comment by Bad-Science** [comment]
For reference, the problem is in this line: https://github.com/YACS-RCOS/yacs/blob/bec5b5e07735e1cad1a7f282f0743f692dcb92b6/app/controllers/api/v5/courses_controller.rb#L7

The regular expression filters out all non-alphanumeric characters. The solution is to either add hyphens to the regular expression or to use a sanitization method like https://apidock.com/rails/ActiveRecord/Base/sanitize/class

The latter is probably the better solution. In that case, the gsub should be removed and the sanitization should probably be moved to the `Course#search` method here:
https://github.com/YACS-RCOS/yacs/blob/bec5b5e07735e1cad1a7f282f0743f692dcb92b6/app/models/course.rb#L12

**Comment by Bad-Science** [comment]
In staging as of #266 . Thanks @shaynajrosado

Will release a patch and deploy tonight @milo-trujillo

**Comment by Bad-Science** [comment]
@milo-trujillo @shaynajrosado Fix has been deployed! see: https://yacs.cs.rpi.edu/#/courses?search=costelloe-kuehn
