### ISSUE TITLE
Global Gallatin Courses

### ISSUE THREAD

**Issue by esilverm** [YACS-RCOS/yacs#323]
Gallatin courses have a possibility of taking place at international campuses.

Making the gallatin course search query [?year=2019&term=SP&limit=0&type=Global+Programs+(IDSEM-UG)](https://gallatin.nyu.edu/academics/courses/jcr:content/content/search.json?year=2019&term=SP&limit=0&type=Global+Programs+(IDSEM-UG)) returns all of the courses that are of this type. This is not really a big issue, it is just something we should probably look into.

**Comment by A1Liu** [comment]
Hmmm for now maybe we just add an additional filter to the query to prevent global programs from showing up? We can't really do much about it right now because the schema hasn't really been updated yet as far as I'm aware. But yeah, we'll probably have to make `school` and `location` independent attributes to take care of that

**Comment by A1Liu** [comment]
have u tried something like `!=` when querying? If that doesn't work, then regex would definitely work for removing items - however, this might not be very fast in python. I think it might be faster to use pandas? for example, we would use [this function](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_json.html) to read in the data, then modify the resulting `Dataframe` object and filter it. I don't know if this method would necessarily be faster, but my intuition says that the string operations in pandas are faster than those in python's normal regex engine

**Comment by esilverm** [comment]
Yeah I tried that. It didn't work. I also tried `!&` which didn't work. In regards to whether we should use regex or pandas I personally have no clue because of the two I only have used regex. You should probably make the choice.

**Comment by esilverm** [comment]
That doesn't seem to be working.

**Comment by A1Liu** [comment]
Yeah I'm beginning to suspect that Gallatin is using something besides the Elastic search API. I looked at this site, and what it said didn't seem to work for me 
http://okfnlabs.org/blog/2013/07/01/elasticsearch-query-tutorial.html#python

**Comment by esilverm** [comment]
I think Gallatin is simply using a standard query string syntax.

**Comment by A1Liu** [comment]
lol we could probably do most of the filtering and translation ourselves using pandas then i guess. I just looked into it, and I'm still not sure whether regex or pandas will be faster - however, I'm almost certain that pandas will be easier to read and maintain. If you want to start working on API translation, you can write it in javascript and I'll write the python code using pandas so that it's readable and stuff

**Comment by A1Liu** [comment]
I'll update the task list and also generate a test file
