### ISSUE TITLE
As an external engineer, I would like to be able to directly link to schedules so that I can direct users to schedules for a set of courses or sections

### ISSUE THREAD

**Issue by copperwater** [YACS-RCOS/yacs#95]
Lots of people, including the Suggestr project, want the ability to have a link to a unique set of schedules. This doesn't seem like it would be too hard to do; we would have to make a /schedules resource be requestable and then the application could pass in course/section IDs as GET parameters:
`http://yacs.server/schedules?section_ids=123,234,345`
I don't know how exactly I would implement this separate resource on the frontend, but it should behave identically to the schedule page, with the user able to go back and pick more classes, etc. There could also be parameters in the link that can be ignored by the backend and used by the frontend, with the `window.location` property, i.e. `section_ids=482,123,684&schedule=4` to automatically go to the 4th schedule.

**Comment by Bad-Science** [comment]
The request should be to `/` as that is the path which corresponds to the app. The same resource would be loaded. 

The different behavior will be determined in javascript, based on the URL. It would make sense to use a fragment instead of a query as it will only have meaning to the front end. The fragment will contain the section or course ids. This would look, roughly, like `https://yacs.cs.rpi.edu/#action=schedule&ids=1,2,3,4,5`

Navigating to this link should not affect the schedule stored in the cookie. i.e., if the schedule data is present in the fragment, the cookie is ignored. Navigating away from the schedule page should remove the fragment.

**Comment by Bad-Science** [comment]
Also, this should not be worked on until after [Beta Release 2]
(https://github.com/aosdict/yacs/milestones/Beta%20Release%202%20(0.6)) is complete

**Comment by copperwater** [comment]
Schedule links have been implemented as of #149 and, later, #202. Links are now accessible to the user as described in #176. The routing stuff implemented last fall has superseded the "request /" thing; schedule links are of the form `/#/schedules?section_ids=238,239,240`.
